language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=sqlite
gemfile:
  - gemfiles/Gemfile.rails-3.x
  - gemfiles/Gemfile.rails-4.x
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake
before_script:
